services:
  postgres:
    container_name: bank_db
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: kyalo
      POSTGRES_PASSWORD: kyalo
      POSTGRES_DB: banksimpledb
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - bank-network

  app:
    image: 'kevinkyalo/bank-app:latest'
    container_name: bank-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banksimpledb
      SPRING_DATASOURCE_USERNAME: kyalo
      SPRING_DATASOURCE_PASSWORD: kyalo
    networks:
      - bank-network
    restart: always

volumes:
  postgres:

networks:
  bank-network:
    driver: bridge
